# job_recommendation.py
import pickle
import pandas as pd
from models import UserScores
from flask_login import current_user

def load_model_and_encoder():
    with open("agents/job_model.pkl", "rb") as f:
        model = pickle.load(f)
    with open("agents/label_encoder.pkl", "rb") as f:
        encoder = pickle.load(f)
    return model, encoder

def recommend_jobs():
    model, encoder = load_model_and_encoder()

    # fetch latest scores of current user
    latest = (
        UserScores.query
        .filter_by(user_id=current_user.id)
        .order_by(UserScores.timestamp.desc())
        .first()
    )

    if not latest:
        return []  # return empty list if no scores

    features = [
        latest.dsa, latest.dbms, latest.os,
        latest.cn, latest.math, latest.aptitude,
        latest.comm, latest.problem_solving,
        latest.creative, latest.hackathons
    ]

    # Convert to DataFrame to match training features
    columns=["DSA","DBMS","OS","CN","Mathmetics","Aptitute","Comm",
               "Problem Solving","Creative","Hackathons","ADVANCED BLOCKCHAIN : A GAME THEORETIC VIEW", "ADVANCED STATISTICAL METHODS", "ALGORITHMS AND PROBLEM SOLVING", "ALGORITHMS AND PROBLEM SOLVING LAB", "APPLICATIONAL ASPECTS OF DIFFERENTIAL EQUATIONS", "APPLIED LINEAR ALGEBRA", "APPLIED MATHEMATICAL METHODS", "APPLIED NUMERICAL METHODS", "APPLIED STATISTICAL MECHANICS", "ARTIFICIAL INTELLIGENCE", "ARTIFICIAL INTELLIGENCE LAB", "AUTOMATA THEORY AND ITS APPLICATIONS", "BASIC NUMERICAL METHODS", "BASICS OF CREATIVE WRITING", "BIG DATA INGESTION", "BIG DATA WITH HADOOP AND SPARK", "BIORISK AND BIOSECURITY", "CIVIL SOCIETY POLITICAL REGIMES AND CONFLICT", "COMPUTER NETWORKS AND INTERNET OF THINGS", "COMPUTER NETWORKS AND INTERNET OF THINGS LAB", "COMPUTER ORGANIZATION AND ARCHITECTURE", "COMPUTER PROGRAMMING", "COMPUTER PROGRAMMING LAB", "CONSTITUTION OF INDIA", "CONSUMER BEHAVIOR AND MARKETING COMMUNICATIONS", "CRYPTOGRAPHY AND NETWORK SECURITY", "CYBER PHYSICAL SYSTEMS", "DATA ANALYTICS AND VISUALIZATION", "DATA COMMUNICATIONS AND NETWORKS", "DATA STRUCTURES AND ALGORITHMS", "DATA STRUCTURES AND ALGORITHMS LAB", "DATABASE MANAGEMENT SYSTEMS", "DATABASE MANAGEMENT SYSTEMS LAB", "DEEP LEARNING", "DESIGN AND ANALYSIS OF ALGORITHMS", "DESIGN AND ANALYSIS OF ALGORITHMS LAB", "DESIGN THINKING AND INNOVATION", "DISCRETE MATHEMATICS", "DISTRIBUTED SYSTEMS", "ELECTRONIC CIRCUITS AND SYSTEMS", "ELECTRONIC CIRCUITS AND SYSTEMS LAB", "ENTREPRENEURSHIP DEVELOPMENT", "ENVIRONMENTAL STUDIES", "FOUNDATION OF FINANCIAL MARKETS", "FRENCH LANGUAGE", "FUNCTIONAL PROGRAMMING", "FUNDAMENTALS OF MANAGEMENT", "GAME THEORY AND ITS APPLICATIONS", "GRAPH THEORY", "GREEN COMPUTING", "HUMAN COMPUTER INTERACTION", "HUMAN VALUES AND ETHICS", "IMAGE PROCESSING", "INDIAN TRADITIONS, CULTURE AND SOCIETY", "INFORMATION RETRIEVAL AND SEMANTIC WEB", "INFORMATION SECURITY", "INFORMATION THEORY AND CODING", "INTERNET OF THINGS APPLICATIONS", "INTRODUCTION TO MACHINE LEARNING", "JAVA PROGRAMMING", "JAVA PROGRAMMING LAB", "KOREAN LANGUAGE", "LINEAR ALGEBRA", "MACHINE LEARNING", "MACHINE LEARNING LAB", "MAJOR PROJECT PART-1", "MAJOR PROJECT PART-2", "MATERIAL SCIENCE", "MATRICES AND DIFFERENTIAL EQUATIONS", "MICROPROCESSORS AND MICROCONTROLLERS", "MICROPROCESSORS AND MICROCONTROLLERS LAB", "MODERN ALGORITHMS", "NETWORK SECURITY AND CRYPTOGRAPHY", "OBJECT ORIENTED PROGRAMMING", "OBJECT ORIENTED PROGRAMMING LAB", "OPERATING SYSTEMS", "OPERATING SYSTEMS LAB", "OPTIMIZATION TECHNIQUES", "PRINCIPLES OF COMMUNICATION SYSTEMS", "PRINCIPLES OF COMMUNICATION SYSTEMS LAB", "PROBABILITY AND RANDOM PROCESSES", "PROJECT MANAGEMENT", "PYTHON PROGRAMMING", "PYTHON PROGRAMMING LAB", "RESEARCH METHODOLOGY", "ROBOTICS AND AUTOMATION", "SECURITY IN CLOUD AND IOT", "SIGNALS AND SYSTEMS", "SMART SYSTEMS AND IOT", "SOFTWARE ENGINEERING", "SOFTWARE ENGINEERING LAB", "STATISTICS FOR DATA SCIENCE", "SUMMER TRAINING VIVA", "THEORY OF COMPUTATION", "UNIX AND SHELL PROGRAMMING", "UNIX AND SHELL PROGRAMMING LAB", "USER EXPERIENCE DESIGN", "VIRTUALIZATION AND CLOUD COMPUTING", "WEB DEVELOPMENT", "WEB DEVELOPMENT LAB", "WEB TECHNOLOGY AND CYBER SECURITY", "WORKPLACE COMMUNICATION"]

        features_df = pd.DataFrame([features], columns=columns)

    if hasattr(model, "predict_proba"):
        probabilities = model.predict_proba(features_df)[0]
        top_3_indices = probabilities.argsort()[-3:][::-1]
        top_3_jobs = encoder.inverse_transform(top_3_indices).tolist()
    else:
        pred = model.predict(features_df)
        top_3_jobs = encoder.inverse_transform(pred).tolist()

    # ✅ Return a list instead of formatted string
    return top_3_jobs
